---
- name: "Docker Install for Pi-4"
  hosts: localhost
  connection: local
  become: yes
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: docker
    docker_install_compose: true
    docker_users:
      - pi
  roles:
    - geerlingguy.pip
    - geerlingguy.docker_arm
